export interface MovieList{
    movieId:number;
    movieTitle:string;
    movieType:string;
    moviePoster:string;
    moviePoster2:string;
    movieRatingOverall:number;
    filmCertificationId:number;
    isDeleted:boolean;
    createDate:Date;
    modifiedDate:Date;
    releaseDate:Date;
    ratingCount:number;
    movieDescription:string;
    actor1:string;
    actor2:string;
    actor3:string;
    director:string;
    musicDirector:string;
}